common: fix return type of the wsgihandler
Should fix issue like:
  TypeError: memoryview: str object does not have the buffer interface

Signed-off-by: Sahid Orentino Ferdjaoui <sferdjaoui@juniper.net>
Change-Id: Ie391654bd00d9e79189611f9a677cc650103c582