Update patch set 5
Patch Set 5:

I kindly ask you to fix pep8 error that was found by non-voting jenkins:

pep8 run-test: commands[0] | flake8
./device_manager/db.py:621:33: E126 continuation line over-indented for hanging indent
                                self.fabric_obj.static_asn_rsvd(asn) is None:
                                ^
ERROR: InvocationError for command /root/contrail/build/debug/config/device-manager/.tox/pep8/bin/flake8 (exited with code 1)

Patch-set: 5
CC: Gerrit User 382 <382@c72cd27d-1743-4a55-84a4-cd13b8400c52>