fixed code so it can compile in both c++11 and c++03
std::array is used in c++11

Moving to C++ 11 results in ambiguity in existing code due to overloading resolution rules

These are some fixes for errors such as

/usr/include/c++/4.8/bits/stl_pair.h:145:64: error: call of overloaded ‘set(const boost::assign_detail::generic_list<char [5]>&)’ is ambiguous
  : first(std::forward<_U1>(__x)), second(std::forward<_U2>(__y)) { }
                                                                ^
/usr/include/c++/4.8/bits/stl_pair.h:145:64: note: candidates are:
In file included from /usr/include/c++/4.8/set:61:0,
                 from src/contrail-common/base/task_annotations.h:9,
                 from controller/src/vnsw/agent/cmn/agent_cmn.h:33,
                 from controller/src/vnsw/agent/oper/ifmap_dependency_manager.cc:5:
/usr/include/c++/4.8/bits/stl_set.h:218:7: note: std::set<_Key, _Compare, _Alloc>::set(std::initializer_list<_Tp>, const _Compare&, const allocator_type&) [with _Key = std::basic_string<cha _Compare = std::less<std::basic_string<char> >; _Alloc = std::allocator<std::basic_string<char> >; std::set<_Key, _Compare, _Alloc>::allocator_type = std::allocator<std::basic_string<char>
       set(initializer_list<value_type> __l,
       ^
/usr/include/c++/4.8/bits/stl_set.h:204:7: note: std::set<_Key, _Compare, _Alloc>::set(std::set<_Key, _Compare, _Alloc>&&) [with _Key = std::basic_string<char>; _Compare = std::less<std::ba_string<char> >; _Alloc = std::allocator<std::basic_string<char> >]
       set(set&& __x)
       ^
/usr/include/c++/4.8/bits/stl_set.h:193:7: note: std::set<_Key, _Compare, _Alloc>::set(const std::set<_Key, _Compare, _Alloc>&) [with _Key = std::basic_string<char>; _Compare = std::less<stbasic_string<char> >; _Alloc = std::allocator<std::basic_string<char> >]
       set(const set& __x)
       ^
/usr/include/c++/4.8/bits/stl_set.h:148:7: note: std::set<_Key, _Compare, _Alloc>::set(const _Compare&, const allocator_type&) [with _Key = std::basic_string<char>; _Compare = std::less<stdasic_string<char> >; _Alloc = std::allocator<std::basic_string<char> >; std::set<_Key, _Compare, _Alloc>::allocator_type = std::allocator<std::basic_string<char> >]
       set(const _Compare& __comp,

Partial-Jira-Bug: CEM-8191

Change-Id: I8066ca9ca828cbc9e7bbf3a2da8a9f01ba7dfe71