CFM: Fix for config is not pushed to SRX
DM was crashing with
self.build_service_chaining_config()
    File
    "/usr/lib/python2.7/site-packages/device_manager/ansible_role_common.py",
    line 1273, in build_service_chaining_config
    pt_obj.logical_routers[idx]})
    TypeError: 'set' object does not support indexing

Fixed the same

Change-Id: If37d42a0d326a8d84969d785f921b612f3a167d0
Closes-Jira-Bug: CEM-4106