build fixes for windows Due to a dependency between boost and winsock that will result in: fatal error C1189: #error :  WinSock.h has already been included The remedy is to include boost/asio before including windows.  Original working changes and change history:  https://github.com/sagarkchitnis/windows/commits/master/controller/
 subsequent changes in https://github.com/codilime/contrail-controller/tree/windows3.1

 Other minor changes TBD.

Change-Id: I6cb5bdaa1fc9169106ce540af558baffc1d4c9c7
Partial-Bug: #1734593