Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> Seems like a failure because of the infra - so thought to recheck.

I see another issue:


Failed to import test module: test.test_vnc_db_mod
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/root/contrail/build/debug/config/fabric-ansible/test/test_vnc_db_mod.py", line 7, in <module>
    from vnc_api.vnc_api import VncApi
  File "/root/contrail/build/debug/config/fabric-ansible/.tox/py36/lib/python3.6/site-packages/vnc_api/vnc_api.py", line 9, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'


looks like all of them use incorrect version of vnc_api (from pypi instead of repo)

Patch-set: 2
Reviewer: Gerrit User 382 <382@c72cd27d-1743-4a55-84a4-cd13b8400c52>