[R1912.LT2] Backport Commits
FIX: added flake8: noqa to device_manager.py and dm_server_args.py

FIX: syntax error in error print message (%%s) -- device_ztp_manager.py

FIX: added skip to test_fip - Skip this until we figure out why new gevent is causing failure

FIX: fixed formatted print statement (missing argument)

FIX: call to mock_zk.ae_id_is_occupied(phy_rtr_name, ae_id)) does not exist -- removing test code

FIX: changed gevent.signal to gevent.signal.signal to fix module called

COMMIT: [config] Removed exceptions for InvalidIPAMRef and FQNStaleIndexError
Closes-Jira-Bug: CEM-11025

InvalidIPAMRef and FQNStaleIndexError are unnecessary exceptions and
Stale subnets are already verified

Change-Id: Ie936255d5a60d37fea4ddb9f8a7e0ba65b279646

Conflicts:
	src/config/api-server/vnc_cfg_api_server/db_manage.py

COMMIT: [api-server]: UT for notify_ae_id function fix

closes-jira-bug: CEM-10940
Change-Id: Id9869c858cbcb0890df7275f909c4dcb6d7c17f3

COMMIT: Allow to manually set VxLAN id back to auto value

Toggling between auto and user-configured VxLAN identifier mode
should not remove the auto assigned value. Administrator should
be able to set the same id which was assigned when auto mode
was enabled.

closes-jira-bug: CEM-10496
Change-Id: Iabba24ab745d38fd43f334474bebbe5c68235e05

COMMIT: Handling ST reinit collisions gracefully + UTs + paths fix

This change was supposed to just add a graceful handling of collisions
in ST reinitialization process + a UT for such scenario.
Thanks to strict UT, I've discovered that RT deleting/populating methods
were implemented incorrectly. Namely, paths they were trying to
delete/create had a doubled prefix, e.g.
"TestRouteTarget/TestRouteTarget/id/bgp/route-target/type0".

closes-jira-bug: CEM-10014
Change-Id: Iafcdad87e9dab9fbd599a8760189c189b51958be

COMMIT: [config] Fix API server cycle import

In case you run the API server main file from the package directory, it
fails due to cycle import error. This is due to the main file name have
the same name as the module: 'vnc_cfg_api_server'.

Change-Id: I14b09f2f9ac6ac079f6be38be756626c3c93d94b
Closes-Jira-Bug: CEM-10357

COMMIT: Validate all Route Targets on GSC ASN update

Patch extends ASN range validation to check VirtualNetwork
import and export target lists

partial-jira-bug: CEM-10864
Change-Id: I43fa96aea425d958f6d5d8d3d04f674634a94f53

COMMIT: Validation of RT in LR on GSC update

Provide validation of user defined route targets
defined in logical router on global system config update.

closes-jira-bug: CEM-10864
Change-Id: Ia0fd83800cdf1471350cbcc8eb1eba5981d62246

COMMIT: Configurable buffer size for ColumnFamily queries

Support for configurable buffer size for db_json_exim
ColumnFamily queries.

closes-jira-bug: CEM-11106
Change-Id: I988aeb2ac974fa7b2408ef97a840690a02db9daa

COMMIT: Handle None value for curr perms or share perms
closes-jira-bug: CEM-11338

Change-Id: I02a1dc4deae124458d822ba00b674fc8f80c8bd1

COMMIT: BGPaaS/BGP Hold Time compliance with the RFC4271

Validate that hold time argument is either zero
or at least three seconds.

closes-jira-bug: CEM-8876
Change-Id: Id6d8279a0cd8bce037e1b2dfbef939c2f1163e0f

COMMIT: FloatingIP list objects which haven't project refs

This patch fixes FloatingIP list crash if floating IP
was created without reference to project.

closes-jira-bug: CEM-10695
Change-Id: Id9af278b748e352674fc599de5691bfd95a8a53a

COMMIT: Fix Virtual Network deletion via heat

This patch provides patch for failing VN deletion via heat.
In case when VN was not found, there was reference
to nonexistent exception which raises NameError.

closes-jira-bug: CEM-12588
Change-Id: Ia2adc17487330391025fbf51b3e4c56ff7c9c2df

Conflicts:
	contrail_heat/resources/contrail.py

COMMIT: Handle Nonetype object
closes-jira-bug: CEM-12943

Change-Id: If3dd31866103a9581e0656b2952105e6ce1520ea

COMMIT: [vnc_openstack] vnc_api_is_authenticated api sever list fix

vnc_api_is_authenticated will try to authenticate against first active
api server instead of trying authenticate against the only first server
in the api server list.

Closes-Jira-Bug: CEM-12127
Change-Id: Ie07abfc0079021cbc88418126997b1ccd01b4af1
(cherry picked from commit 6d272eb13ba98015ba560a125b60bc0d75553b22)

Conflicts:
	neutron_plugin_contrail/common/utils.py

COMMIT: [api-server]: Remove redundant dbe_read

During vmi_create and vmi_read operations, we check for existing vlans
for which we do dbe_list of VMIs. This patch removes redundant db_read
of these vmis which was being done after dbe_list.
This brings 3x improvement for scale tests done for 500 vmis by Senthil.

Closes-Jira-Bug: CEM-13231
Change-Id: Iba26be49fb50b407e668612f61cd957edaa29168

COMMIT: [api-server]: Remove redundant dbe_read

During vmi_create and vmi_read operations, we check for existing vlans
for which we do dbe_list of VMIs. This patch removes redundant db_read
of these vmis which was being done after dbe_list.
This brings 3x improvement for scale tests done for 500 vmis by Senthil.

Closes-Jira-Bug: CEM-13231
Change-Id: Iba26be49fb50b407e668612f61cd957edaa29168

COMMIT: Handle None type objects
closes-jira-bug: CEM-11970
closes-jira-bug: CEM-14383

Fixing
route_targets = obj.get(field, {}).get('route_target', [])
AttributeError: 'NoneType' object has no attribute 'get'

Change-Id: Iffcc4f195795a8845c35123431d7ffbb2a7e68cc