NULL Check for VRF. Closes-bug: #1408693
Change-Id: Ie8393e1cae91e0faf240ebd4eea73f6fdcbb6997

* Add vmware physical interface mac receive route in all VRF.
  Test case for same

Change-Id: I4b334da176fd35dd27763237fdbb607527049dc2

1)Use ToString to get ff:ff:ff:ff:ff:ff instead of GetAddressString for
ingress replication subscription.

2) Fix compilation error. Use sub_type in VmInterface to ignore l2 update for TOR interfaces.

Change-Id: I8760cf34bffb0f5627bf90b9a18adb84a2d001af

Support for VMI sub-interfaces

Renamed sub_type_ in VM Interface to device_type_. It will contain
information about the type of interface for the VMI

Add new field vif_type_ for VM Interface. The type can be INSTANCE,
BAREMETAL, GATEWAY etc...

Added support for VMI Sub-Interface based on VLANs

VmInterface::IFNodeToReq will now compute device_type_ and vmi_type_
based on external-message (PortAdd) and parent object in the
configuration.

Shuffled code in VMI::IFNodeToReq to make it modular.

Change-Id: I4e2ce2bc6b7b80f8dd2809b28b377284fddc0742

Fix build break in R2.1.

Change-Id: I7e3af7b57a53d566de6b827c905305022549c1e5

Removing TSN check for VM interface.
Change-Id: If77ad528745e60fb04b81e7b190ff56870d7d521

In ksync unresolved reference, check NH when mac is zero.
Do not stitch mac for routes pointing to pkt0.
Closes-bug: #1411828

Change-Id: I72c62b8ddc8c6a3f62a1e23d73c0271909442ffb

Correct the comparator in EvpnDerivedPath.
Do not program l2 routes in TSN on vxlan change.
Change-Id: I467eeb9813ebaf63d2c8cc5e2844a82f61a15fd8

Add debug logs

Debug logs to catch error in RouteFlowUpdate::Notify()

Change-Id: I29fea6da793362f84f93d61c02cf090198b84966

Fix for crash in RouteFlowUpdate::Notify

In crash scenario, we have following two threads,

Thread-1
--------
   /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                                                   partition=0x7ffedc01a830,
                                                   e=0x7ffedc34cc90)
    at controller/src/vnsw/agent/pkt/flow_table.cc:1984

Thread-2
--------
tbb::spin_rw_mutex_v3::scoped_lock::scoped_lock (this=0x7ffeedefb970,
                                                 m=..., write=true) at
build/include/tbb/spin_rw_mutex.h:99
(this=0x7ffedc0081a0, listener=2) at controller/src/db/db_table.cc:64

Agent uses only uses DBTable partition 0 for DBEntries. But, the DBTable
walk-done callback can happen in context of any of the partitions.

In RouteFlowUpdate::WalkDone, we delete RouteFlowUpdate object.
Unregister for the Inet/Bridge DBTable is called in destructor of
RouteFlowInfo object.

In crash scenario, we have following sequence
1. RouteFlowUpdate::Notify is invoked as part of notification of a DBEntry
from DBTableBase::ListenerInfo::RunNotify.
2. DBTableBase::ListenerInfo::RunNotify holds mutex for vector of
listeners
3. In parallel RouteFlowUpdate::WalkDone is invoked in another task
context.
4. In WalkDone, InetRouteFlowUpdate is deleted. The destructor for
InetRouteFlowTable clears vtable first and then invokes destructor for
base class. The unregister for DBTable happens in base class.

By the time, RunNotify is called the vtable is cleared. This results in
crash since vtable is cleared.

Fix:
----
Unregister to the DBTable is called from WalkNotify itself. As a result,
unregister is done even while vtable is intact.

closes-bug: #1410302
Change-Id: I9e8903b560df452de270728d6b5730515c971bbc

Fix to use listener id for setting state in multicast.
Issue was because wrong id was set in state.
CLoses-bug: 1412294

Change-Id: Ib9524307303ac5e701e2af3bead12bd5c7b9cb77

For Logical and Physical interfaces, ensure that display name is unique within the physical router. Agent uses this as a key. Change of display name for these interfaces is also not allowed.
Closes-bug: #1403252

Change-Id: Id033b53f25af74bd79cfef56278edb3754546ba5

* If interface is oper down, then all the vrf assign entries were
  getting deleted, and once oper state comes up again since we
  dont go config sync again, vrf assign entries was not getting added
  again. Dont remove VRF assign entries when agent goes oper down.
  Test case to verify the same
Closes-bug:#1405137

Change-Id: I22381e132af5a02cbe7d6c884033cf46165a51fe

Agent Crash has happened because we are accessing VM interface pointer after it has been deleted.
As part of Interface Delete notification handling, we were not deleting interface from UVE data-structure if its VM is marked for delete and we were removing the reference on the interface.
Made changes to ensure that VM interface pointer is removed from UVE data-structure even when VM is marked for delete.
Closes-Bug: #1412132

Change-Id: If11aa5d690d8028c1b1e61bb043b4f43e5e2a6ec

Copy tunnel bmap from evpn route path to bridge path(evpnderivedpath).
This helps if rebake is individually done on bridge entry(via some walk) then
tunnel type is derived based on parent tunnel_bmap.

Change-Id: I0a6990f8bea1febab402715dcdfc5d632e4397e7

Ensure packets destined across VN are routed

Set Proxy flag and reset Flood flags if packets are destined across VN

Change-Id: I4c8ee9bad536f7354c194558ebba8ffb6658764b

Dont use tunnel type for multicast path comparision.
Only vxlan_id needs to be compared.

Change-Id: I4fd38c6ac4a7e106a394ed492acf73cfb67de479

Allocate EVPN mpls label when multicast object is created because of TOR
addition. Currently EVPN mpls label was created when VM interface was added,
however on TSN node VM interfaces are not allocated and TOR addition is the
driving point.
Closes-bug: 1413070

Change-Id: I4d4fbc108077597f2e435c04152abb7ce1ad1dee

Fix error in ICMP error generated

Fix network order for the source-ip in packet generated
Fix the checksum in inner payload

Change-Id: I0d611d92cb8082cfb100c1d4d10b03df8b0a8785

Add dest-vn name for default routes

Change-Id: Id9c08df5c6d0eacb927a1f7276521fa4e29fbb6b

Get reference to boost parameters instead of get by value

Change-Id: Ie4d4e7ea045d23ee1e9cfe029ed9ee6f163aed72

Send TOR agent UVEs with the configured agent_name, without this the process_status info for TOR agent was added to the vrouter agent.

Change-Id: Icf9a2072aaffa71891dd03daa15d92df3b43fd42

* Make vx_lan flag as key variable for vrf NH
* Fix gateway interface creation, due to wrong link parsing from
  logical interface to physical route
* Fix ping failure to gateway address
* Test case for same

Change-Id: Idd858092c025ab69601c6bb5213d9eed5a600674

Replace logs with traces in agent_route_walker.

Change-Id: I978d23288d6189947e050744c1c3aacf4f7ab062

Force RESYNC on VMI added from config

For VM Interface, the VN and VRF link are built when RESYNC is called.
If the link from sub-interface VMI to parent interface VMI is received
last, only Add-Change is called for the VMI sub-interface.

Modifying PostAdd() for VMInterface to force Change (RESYNC in-turn) for
VMInterface

Add UT for the same.

Change-Id: I6e074501fb10d7d1b48f86111fd0ef086c69aa56

Update introspect for logical-ports

Change-Id: I030802b95c227a8aacb44c6d0e61f51754123a4a

Send VrouterStatsAgent UVE from TOR agent. The tor agent name had to be used,
instead of the host name for these to be reflected under the correct head.

Closes-Bug :#1414344

Change-Id: If6ddeb69e75591bfb4e99f720d98461e456abc7c

patch for VGW to work
Change-Id: I5f2bf6f27dd722b564448d7a108227e9be520116

Fixing compare logic for vlan port bindings

fixing and simplifing logic to compare difference in vlan port
bindings between TOR and TOR agent.

fixing display to use binding_table instead of ovs_binding_table
to avoid invalid logical switch pointer access.

Change-Id: I756f9493d30aa7fb7aeefb81000a2713a52d7330

OVS delete unicast local route on device_vn delete

adding logic to trigger delete unicast local routes on deletion
of device_vn or logical switch, for immediate cleanup of ovsdb
states.
Additionaly avoid taking ksync reference to logical switch for
self exported routes.

Change-Id: I842da146b69333c4b8c9d9e23968ced18326d733
Closes-Bug: 1413590