Don't threat maybe-uninitialized warning as error to workaround boost-related bug
Workarounding following build issue:

g++ -o build/production/vnsw/agent/oper/agent_sandesh.o -c -g -O3 -Wall
-Werror -Wsign-compare -Wno-unused-local-typedefs -DLINUX -fno-exceptions
-Ibuild/production -Ibuild/production/base/sandesh
-Icontroller/src/base/sandesh -Ibuild/production/dns -Icontroller/src/dns
-Ibuild/production/http/client -Icontroller/src/http/client
-Ibuild/production/ifmap -Icontroller/src/ifmap -Ibuild/production/schema
-Icontroller/src/schema -Ibuild/production/sandesh -Icontroller/src/sandesh
-Ibuild/production/vnsw/agent -Icontroller/src/vnsw/agent
-Ibuild/production/vnsw/agent/oper -Icontroller/src/vnsw/agent/oper
-Ibuild/production/vnsw/agent/cmn -Icontroller/src/vnsw/agent/cmn
-Ibuild/production/vnsw/agent/uve -Icontroller/src/vnsw/agent/uve
-Ibuild/production/vnsw/agent/openstack -Icontroller/src/vnsw/agent/openstack
-Ibuild/production/vrouter/sandesh -Ivrouter/sandesh
-Ibuild/production/vnsw/agent/nexthop_server
-Icontroller/src/vnsw/agent/nexthop_server
-Ibuild/production/vnsw/agent/vrouter/ksync/linux
-Icontroller/src/vnsw/agent/vrouter/ksync/linux -Ibuild/include/thrift
-Ivrouter/include -Icontroller/src -Ibuild/include -Icontroller/lib
controller/src/vnsw/agent/oper/agent_sandesh.cc
controller/src/vnsw/agent/oper/agent_sandesh.cc: In member function 'virtual bool AgentVnSandesh::Filter(const DBEntryBase*)':
controller/src/vnsw/agent/oper/agent_sandesh.cc:80:9: error: 'result' may be used uninitialized in this function [-Werror=maybe-uninitialized]
         if (((vn->GetVxLanId()) == boost::lexical_cast<int>(vxlan_id_)) == false) {
         ^
cc1plus: all warnings being treated as errors
scons: *** [build/production/vnsw/agent/oper/agent_sandesh.o] Error 1

Partial-Bug: #1603881
Change-Id: I6e0c8440d0286e804c2bd30c90971ab6faf8cb1b