common: pin to a supported version of gevent
Should fix such error:
  TypeError: memoryview: a bytes-like object is required, not 'str'

Signed-off-by: Sahid Orentino Ferdjaoui <sferdjaoui@juniper.net>
Change-Id: I51bd51b81fcde2a8645f08ecddb6e625168fe6a0