[Fabric] change the route-distinguisher value
VXLAN-ID being used set the route-distinguisher for vni's greater than 65535 config is failing.

So using the virtual_network_id for route-distinguisher which is used in other templates.

Error:
  'route-distinguisher'
    RT Instance: invalid RD number value at '7328642' not in range 0 to 65535
    error: configuration check-out failed

target-release: R2002
closes-jira-bug: CEM-12433

Change-Id: I83c2f83a034ad7eb19fc7866a03f2321791ad257