config-ut: monkey patch in common test-case definition file
Not doing this will lead to error as below as threading.local
does not correspond to gevent.local

This was working earlier likely to due order of imports elsewhere.

  File "/home/jenkins/workspace/ci-contrail-controller-unittest/repo/build/debug/config/api-server/.venv/local/lib/python2.7/site-packages/bottle.py", line 2900, in run
    raise RuntimeError(msg)
RuntimeError: Bottle requires gevent.monkey.patch_all() (before import)
    server.run(app)

Change-Id: Ib142746c7a9f946daf61f0aee923f1d2b3614a49