Update patch set 2
Patch Set 2:

Seems like a failure because of the infra - so thought to recheck.
Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "test/test_case.py", line 33, in setUpClass
        super(DMTestCase, cls).setUpClass(extra_config_knobs=extra_config)
      File "/home/centos/contrail-5.2.0/build/debug/config/device-manager/.tox/py27/lib/python2.7/site-packages/cfgm_common/tests/test_common.py", line 762, in setUpClass
        db=db)
      File "/home/centos/contrail-5.2.0/build/debug/config/device-manager/.tox/py27/lib/python2.7/site-packages/cfgm_common/tests/test_common.py", line 252, in create_api_server_instance
        ret_server_info['service_port'])
      File "/home/centos/contrail-5.2.0/build/debug/config/device-manager/.tox/py27/lib/python2.7/site-packages/cfgm_common/tests/test_utils.py", line 843, in block_till_port_listened
        raise Exception("port %s not up after %d retries" % (server_port, retries))
    Exception: port 47584 not up after 30 retries

Patch-set: 2