Fix compilation error on redhat controller/src/vnsw/agent/oper/mirror_table.cc:62:14: note: ‘nh’ was declared here      NextHop *nh;               ^
Change-Id: I31c5611b288d1beb89e3b5bffa1384caa7570d13
(cherry picked from commit b006053f4bd71b9088f9ad05187e3ad88bc09426)