Update patch set 3
Patch Set 3:

Failed contrail-sanity-centos7-k8s because

test_ingress_ip_assignment failed
 - AttributeError: 'NoneType' object has no attribute 'get_namespace_info'

Failed contrail-vnc-build-unittest-centos7 because

vnc_cfg_api_server.tests.test_rbac.TestRbacAaaModeAdminOnly failed
 - port 41952 not up after 30 retries

Patch-set: 3