Update patch set 12
Patch Set 12:

[ERROR] Failed to execute goal on project juniper-contrail-api: Could not resolve dependencies for project net.juniper.contrail:juniper-contrail-api:jar:3.0-SNAPSHOT: Could not transfer artifact org.glassfish.jersey.core:jersey-client:jar:2.10.1 from/to central (https://repo.maven.apache.org/maven2): Connection to https://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
error: Bad exit status from /var/tmp/rpm-tmp.6FCGtJ (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.6FCGtJ (%build)
make: *** [rpm-contrail-vcenter-plugin] Error 1

Patch-set: 12
Reviewer: Gerrit User 299 <299@c72cd27d-1743-4a55-84a4-cd13b8400c52>