Handle None type objects closes-jira-bug: CEM-11970 closes-jira-bug: CEM-14383
Fixing
route_targets = obj.get(field, {}).get('route_target', [])
AttributeError: 'NoneType' object has no attribute 'get'

Change-Id: Iffcc4f195795a8845c35123431d7ffbb2a7e68cc
(cherry picked from commit a28c58d14ad3d6bca0e04aec47c8a8716b9ee477)