Update patch set 10
Patch Set 10: -Code-Review

pep8 issue:

pep8 run-test-pre: PYTHONHASHSEED='277529612'
pep8 run-test: commands[0] | flake8
./nodemgr/common/cassandra_manager.py:5:1: F401 're' imported but unused
import re
^
ERROR: InvocationError for command /root/work/build/debug/nodemgr/.tox/pep8/bin/flake8 (exited with code 1)

Patch-set: 10
Reviewer: Gerrit User 382 <382@c72cd27d-1743-4a55-84a4-cd13b8400c52>
Label: Code-Review=0