Update patch set 1
Patch Set 1: Code-Review-1

pep8 run-test-pre: PYTHONHASHSEED='183242939'
pep8 run-test: commands[0] | flake8
./cfgm_common/tests/unit/test_dependency_tracker.py:8:1: I100 Import statements are in the wrong order. 'import unittest' should be before 'import six' and in a different group.
import unittest
^
./cfgm_common/tests/unit/test_dependency_tracker.py:8:1: I201 Missing newline between import groups. 'import unittest' is identified as Stdlib and 'import six' is identified as Third Party.
import unittest
^
ERROR: InvocationError for command /root/contrail/build/debug/config/common/.tox/pep8/bin/flake8 (exited with code 1)

Patch-set: 1
Reviewer: Gerrit User 382 <382@c72cd27d-1743-4a55-84a4-cd13b8400c52>
Label: Code-Review=-1